# **Project Overview**

This project is a beginner-friendly Sales Data Analysis project developed using Python and the Pandas library. The objective is to demonstrate the complete data analysis workflow, including loading data, exploring the dataset, cleaning missing values and duplicates, analyzing sales performance, and generating meaningful business insights.

The project uses a CSV file containing sales records and applies Python data analysis techniques to calculate revenue, identify the best-performing product, and summarize key findings. This project helped strengthen practical skills in data manipulation, data cleaning, and exploratory data analysis using Pandas.

# **Project Objectives**
Load and read a sales dataset from a CSV file using Pandas.
Explore the dataset by examining its shape, columns, and data types.
Clean the data by handling missing values and removing duplicate records.
Analyze sales performance by calculating total revenue and identifying the best-selling product.
Generate a simple report with key insights and results.
Develop hands-on experience with Python for real-world data analysis tasks.

In [2]:
# load dataset using pandas library
import pandas as pd
df = pd.read_csv('/content/sales_data (1).csv')
df

          Date     Product  Quantity  Price Customer_ID Region  Total_Sales
0   2024-01-01       Phone         7  37300     CUST001   East       261100
1   2024-01-02  Headphones         4  15406     CUST002  North        61624
2   2024-01-03       Phone         2  21746     CUST003   West        43492
3   2024-01-04  Headphones         1  30895     CUST004   East        30895
4   2024-01-05      Laptop         8  39835     CUST005  North       318680
..         ...         ...       ...    ...         ...    ...          ...
95  2024-04-05      Tablet         8  20770     CUST096  North       166160
96  2024-04-06  Headphones         1   7647     CUST097   West         7647
97  2024-04-07      Tablet         5  27196     CUST098   East       135980
98  2024-04-08     Monitor         1  30717     CUST099  North        30717
99  2024-04-09  Headphones         5  23376     CUST100  South       116880

[100 rows x 7 columns]

# **Data Description**

* Date
* Product
* Quantity

*   Price
*  Custome Id
* Region
* Total sales

In [8]:
df.shape # check the no of columns and rows

(100, 7)

In [9]:
df.columns # columns names

Index(['Date', 'Product', 'Quantity', 'Price', 'Customer_ID', 'Region',
       'Total_Sales'],
      dtype='object')

In [10]:
df.dtypes # data types

Date           object
Product        object
Quantity        int64
Price           int64
Customer_ID    object
Region         object
Total_Sales     int64
dtype: object

# **Statistical informations**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Date         100 non-null    object
 1   Product      100 non-null    object
 2   Quantity     100 non-null    int64
 3   Price        100 non-null    int64
 4   Customer_ID  100 non-null    object
 5   Region       100 non-null    object
 6   Total_Sales  100 non-null    int64
dtypes: int64(3), object(4)
memory usage: 5.6+ KB

**Number of Rows and Columns**
* Displays the total number of entries (rows).
* Shows the number of columns.

**Column Names**
* Lists every column in the dataset.

**Non-Null Count**
* Shows how many non-missing values are present in each column.
* Helps identify missing data.

**Data Types (dtype)**
* Shows the data type of each column.

**Examples:**

* int64 → Integer
* float64 → Decimal numbers
* object → Text/String
* bool → True/False
* datetime64 → Date and Time

**Memory Usage**

Displays the approximate memory used by the DataFrame.

In [4]:
df.describe()

         Quantity         Price    Total_Sales
count  100.000000    100.000000     100.000000
mean     4.780000  25808.510000  123650.480000
std      2.588163  13917.630242  100161.085275
min      1.000000   1308.000000    6540.000000
25%      2.750000  14965.250000   39517.500000
50%      5.000000  24192.000000   97955.500000
75%      7.000000  38682.250000  175792.500000
max      9.000000  49930.000000  373932.000000

# **Numerical columns:**

* Quantity
* Price
* Total_Sales

In [5]:
# check the null values in columns
df.isnull().sum()

Date           0
Product        0
Quantity       0
Price          0
Customer_ID    0
Region         0
Total_Sales    0
dtype: int64

Dataset doesnt contains null values

In [6]:
df.duplicated().sum() # check the duplicates

np.int64(0)

**Total Revenue**

In [12]:
df['Revenue'] = df['Quantity'] * df['Price'] # add new column name revenue
df

,Date,Product,Quantity,Price,Customer_ID,Region,Total_Sales,Revenue
0,2024-01-01,Phone,7,37300,CUST001,East,261100,261100
1,2024-01-02,Headphones,4,15406,CUST002,North,61624,61624
2,2024-01-03,Phone,2,21746,CUST003,West,43492,43492
3,2024-01-04,Headphones,1,30895,CUST004,East,30895,30895
4,2024-01-05,Laptop,8,39835,CUST005,North,318680,318680
...,...,...,...,...,...,...,...,...
95,2024-04-05,Tablet,8,20770,CUST096,North,166160,166160
96,2024-04-06,Headphones,1,7647,CUST097,West,7647,7647
97,2024-04-07,Tablet,5,27196,CUST098,East,135980,135980
98,2024-04-08,Monitor,1,30717,CUST099,North,30717,30717
99,2024-04-09,Headphones,5,23376,CUST100,South,116880,116880

In [15]:
total_revenue = df["Revenue"].sum()
print("Total Revenue:", total_revenue) # calculate the total revenue

Total Revenue: 12365048

**Best selling Product and Revenue**

In [16]:
best_product = df.groupby("Product")["Revenue"].sum().idxmax()
best_revenue = df.groupby("Product")["Revenue"].sum().max()

print("Best Product:", best_product)
print("Revenue:", best_revenue)

Best Product: Laptop
Revenue: 3889210

**Total Quantity Sold**

In [17]:
total_quantity = df["Quantity"].sum()
print("Total Quantity Sold:", total_quantity)

Total Quantity Sold: 478

**Sales by region**

In [18]:
df.groupby("Region")["Revenue"].sum()

Region
East     2519639
North    3983635
South    3737852
West     2123922
Name: Revenue, dtype: int64